### ISSUE TITLE
uninitialized constant `Decidim::Proposals::Admin::Picker` (NameError)

### ISSUE THREAD

**Issue by decentral1se** [digidemlab/decidim-module-budgets_paper_ballots#10]
While running under `0.28-stable`.

```
App 129313 output: Error: The application encountered the following error: uninitialized constant Decidim::Proposals::Admin::Picker (NameError)
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/decidim-module-budgets_paper_ballots-3e5d2794f43b/app/controllers/decidim/budgets/admin/projects_controller.rb:9:in `<class:ProjectsController>'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/decidim-module-budgets_paper_ballots-3e5d2794f43b/app/controllers/decidim/budgets/admin/projects_controller.rb:7:in `<module:Admin>'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/decidim-module-budgets_paper_ballots-3e5d2794f43b/app/controllers/decidim/budgets/admin/projects_controller.rb:5:in `<module:Budgets>'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/decidim-module-budgets_paper_ballots-3e5d2794f43b/app/controllers/decidim/budgets/admin/projects_controller.rb:4:in `<module:Decidim>'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/decidim-module-budgets_paper_ballots-3e5d2794f43b/app/controllers/decidim/budgets/admin/projects_controller.rb:3:in `<main>'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies/interlock.rb:13:in `loading'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/engine.rb:493:in `block (2 levels) in eager_load!'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/engine.rb:492:in `each'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/engine.rb:492:in `block in eager_load!'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/engine.rb:489:in `each'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/engine.rb:489:in `eager_load!'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/engine.rb:358:in `eager_load!'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/application/finisher.rb:134:in `each'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/application/finisher.rb:134:in `block in <module:Finisher>'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
App 129313 output:     /home/decidim/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
```

**Comment by reinefjord** [comment]
fixed in 47f33a43371063d05d0729e24b8d4acc7920c25d
